### ISSUE TITLE
FOIA Annual Report - tables run off page

### ISSUE THREAD

**Issue by JacobsUSABGC** [atbcb/usab-uswds#593]
Several tables in html version of FOIA Annual Report (FY2019) run off side of page. < https://beta.access-board.gov/about/foia-report.html >

**Comment by bruce-usab** [comment]
Thanks for adding these as issues!

**Comment by bruce-usab** [comment]
Putting on the queue for Wednesday discussion w/ @apburnes since it looks to me like USA-TABLE should be adding scroll bars automatically when needed.  I tried adding CSS manually and with class calls to no effect, please see:

- https://github.com/atbcb/usab-uswds/blob/bruce-foia-report/_pages/foia-report.md
- https://federalist-e3fba26d-2806-4f02-bf0e-89c97cfba93c.app.cloud.gov/preview/atbcb/usab-uswds/bruce-foia-report/about/foia-report.html

**Comment by bruce-usab** [comment]
trick is that overflow-x needs to be applied to a div that wraps the table -- will be closing this soon
